<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="PiperModule_Test" Id="{938c15c7-47ae-07e3-18c2-da354fdb321f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PiperModule_Test EXTENDS FB_TestSuite
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Copyright (c) 2024 Loupe (https://loupe.team), provided under the MIT License.
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>