<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Piper_EM" Id="{7bb4d6f6-6e3f-4f5e-9e90-54bf176f9f7c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Piper_EM EXTENDS PiperModule
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	task: REFERENCE TO TaskFB;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_init" Id="{88ddee25-345b-4bc5-ae36-4ed6c81c19d2}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	machineIn : REFERENCE TO Piper;
	taskFB : REFERENCE TO TaskFB;
//	context : IPluginRunner;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[THIS^.setContext(taskFB);
task REF= taskFB;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>